//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_OpticaEntities : DbContext, IDisposable
    {
        public DB_OpticaEntities()
            : base("name=DB_OpticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OPT_Comuna> OPT_Comuna { get; set; }
        public virtual DbSet<OPT_Cuota> OPT_Cuota { get; set; }
        public virtual DbSet<OPT_Pago> OPT_Pago { get; set; }
        public virtual DbSet<OPT_Region> OPT_Region { get; set; }
        public virtual DbSet<OPT_Rol> OPT_Rol { get; set; }
        public virtual DbSet<OPT_Sucursal> OPT_Sucursal { get; set; }
        public virtual DbSet<OPT_Usuario> OPT_Usuario { get; set; }
        public virtual DbSet<OPT_UsuarioSucursal> OPT_UsuarioSucursal { get; set; }
        public virtual DbSet<OPT_EmpresaSucursal> OPT_EmpresaSucursal { get; set; }
        public virtual DbSet<OPT_Empresa> OPT_Empresa { get; set; }
        public virtual DbSet<OPT_Abono> OPT_Abono { get; set; }
        public virtual DbSet<OPT_FormaPago> OPT_FormaPago { get; set; }
        public virtual DbSet<OPT_EstadoOT> OPT_EstadoOT { get; set; }
        public virtual DbSet<OPT_OrdenDeTrabajo> OPT_OrdenDeTrabajo { get; set; }
        public virtual DbSet<OPT_Defontana> OPT_Defontana { get; set; }
        public virtual DbSet<OPT_Anamnesis> OPT_Anamnesis { get; set; }
        public virtual DbSet<OPT_Cliente> OPT_Cliente { get; set; }
        public virtual DbSet<OPT_RecetaCristales> OPT_RecetaCristales { get; set; }
        public virtual DbSet<OPT_BitacoraOT> OPT_BitacoraOT { get; set; }
        public virtual DbSet<OPT_OrdenDeTrabajoDetalle> OPT_OrdenDeTrabajoDetalle { get; set; }
        public virtual DbSet<OPT_ProductoDocumento> OPT_ProductoDocumento { get; set; }
        public virtual DbSet<OPT_ProductoIngresoEgreso> OPT_ProductoIngresoEgreso { get; set; }
        public virtual DbSet<OPT_TipoDocumento> OPT_TipoDocumento { get; set; }
        public virtual DbSet<OPT_Producto> OPT_Producto { get; set; }
        public virtual DbSet<OPT_RegularizaProducto> OPT_RegularizaProducto { get; set; }
        public virtual DbSet<OPT_Atencion> OPT_Atencion { get; set; }
    
        public virtual ObjectResult<sp_ListaDeudores_Result> sp_ListaDeudores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaDeudores_Result>("sp_ListaDeudores");
        }
    
        public virtual ObjectResult<sp_DetalleDeudores_Result> sp_DetalleDeudores(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DetalleDeudores_Result>("sp_DetalleDeudores", idEmpresaParameter);
        }
    
        public virtual ObjectResult<sp_OTPeriodo_Result> sp_OTPeriodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OTPeriodo_Result>("sp_OTPeriodo");
        }
    
        public virtual ObjectResult<sp_OTPeriodoMes_Result> sp_OTPeriodoMes(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OTPeriodoMes_Result>("sp_OTPeriodoMes", idSucursalParameter);
        }
    
        public virtual ObjectResult<SP_OTEliminar_Result> SP_OTEliminar(Nullable<int> idOT)
        {
            var idOTParameter = idOT.HasValue ?
                new ObjectParameter("IdOT", idOT) :
                new ObjectParameter("IdOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OTEliminar_Result>("SP_OTEliminar", idOTParameter);
        }
    
        public virtual ObjectResult<SP_OTActualizaStock_Result> SP_OTActualizaStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OTActualizaStock_Result>("SP_OTActualizaStock");
        }
    }
}
