//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_Usuario()
        {
            this.OPT_UsuarioSucursal = new HashSet<OPT_UsuarioSucursal>();
        }
    
        public string RutUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
        public string Nombre { get; set; }
        public string Mail { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual OPT_Rol OPT_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_UsuarioSucursal> OPT_UsuarioSucursal { get; set; }
    }
}
