//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_BitacoraOT
    {
        public long idBitacoraOT { get; set; }
        public long idOT { get; set; }
        public int idEstado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Responsable { get; set; }
        public string Observacion { get; set; }
    
        public virtual OPT_EstadoOT OPT_EstadoOT { get; set; }
        public virtual OPT_OrdenDeTrabajo OPT_OrdenDeTrabajo { get; set; }
    }
}
