//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_Producto()
        {
            this.OPT_OrdenDeTrabajoDetalle = new HashSet<OPT_OrdenDeTrabajoDetalle>();
            this.OPT_ProductoIngresoEgreso = new HashSet<OPT_ProductoIngresoEgreso>();
            this.OPT_RegularizaProducto = new HashSet<OPT_RegularizaProducto>();
        }
    
        public long idProducto { get; set; }
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<int> Entrada { get; set; }
        public Nullable<int> Salida { get; set; }
        public Nullable<int> Stock { get; set; }
        public int StockMinimo { get; set; }
        public int StockMaximo { get; set; }
        public bool ControlStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_OrdenDeTrabajoDetalle> OPT_OrdenDeTrabajoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_ProductoIngresoEgreso> OPT_ProductoIngresoEgreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_RegularizaProducto> OPT_RegularizaProducto { get; set; }
    }
}
