//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_Cliente()
        {
            this.OPT_Anamnesis = new HashSet<OPT_Anamnesis>();
            this.OPT_OrdenDeTrabajo = new HashSet<OPT_OrdenDeTrabajo>();
            this.OPT_RecetaCristales = new HashSet<OPT_RecetaCristales>();
            this.OPT_Atencion = new HashSet<OPT_Atencion>();
        }
    
        public string RutCliente { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idComuna { get; set; }
        public string Celular { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string TipoPrevision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_Anamnesis> OPT_Anamnesis { get; set; }
        public virtual OPT_Comuna OPT_Comuna { get; set; }
        public virtual OPT_Empresa OPT_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_OrdenDeTrabajo> OPT_OrdenDeTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_RecetaCristales> OPT_RecetaCristales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_Atencion> OPT_Atencion { get; set; }
    }
}
