//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Anamnesis
    {
        public long idAnamnesis { get; set; }
        public string RutCliente { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string RutUsuario { get; set; }
        public int idSucursal { get; set; }
        public int idEmpresa { get; set; }
        public bool hipertension { get; set; }
        public bool Diabetes { get; set; }
        public bool Alergias { get; set; }
        public bool Lentes { get; set; }
        public string Observacion { get; set; }
    
        public virtual OPT_Empresa OPT_Empresa { get; set; }
        public virtual OPT_Sucursal OPT_Sucursal { get; set; }
        public virtual OPT_Cliente OPT_Cliente { get; set; }
    }
}
