//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_ProductoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_ProductoDocumento()
        {
            this.OPT_ProductoIngresoEgreso = new HashSet<OPT_ProductoIngresoEgreso>();
        }
    
        public long idProductoDocumento { get; set; }
        public int idTipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public int IngresoEgreso { get; set; }
        public string Proveedor { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_ProductoIngresoEgreso> OPT_ProductoIngresoEgreso { get; set; }
        public virtual OPT_TipoDocumento OPT_TipoDocumento { get; set; }
    }
}
