//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_RegularizaProducto
    {
        public long idRegularizaProducto { get; set; }
        public long idProducto { get; set; }
        public int StockAnterior { get; set; }
        public int StockNuevo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Responsable { get; set; }
        public string Motivo { get; set; }
    
        public virtual OPT_Producto OPT_Producto { get; set; }
    }
}
