//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_ProductoIngresoEgreso
    {
        public long idProductoIngreso { get; set; }
        public long idProductoDocumento { get; set; }
        public long idProducto { get; set; }
        public int Cantidad { get; set; }
        public int ValorUnitario { get; set; }
    
        public virtual OPT_ProductoDocumento OPT_ProductoDocumento { get; set; }
        public virtual OPT_Producto OPT_Producto { get; set; }
    }
}
