//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_RecetaCristales
    {
        public long idRecetaCristales { get; set; }
        public Nullable<long> idOT { get; set; }
        public string LejosODEsferico { get; set; }
        public string LejosODCilindro { get; set; }
        public string LejosODEje { get; set; }
        public string LejosODObservacion { get; set; }
        public string LejosOIEsferico { get; set; }
        public string LejosOICilindro { get; set; }
        public string LejosOIEje { get; set; }
        public string LejosOIObservacion { get; set; }
        public string LejosDPEsferico { get; set; }
        public string LejosDPObservacion { get; set; }
        public string CercaODEsferico { get; set; }
        public string CercaODCilindro { get; set; }
        public string CercaODEje { get; set; }
        public string CercaODObservacion { get; set; }
        public string CercaOIEsferico { get; set; }
        public string CercaOICilindro { get; set; }
        public string CercaOIEje { get; set; }
        public string CercaOIObservacion { get; set; }
        public string LejosADDEsfera { get; set; }
        public string CercaDPEsferico { get; set; }
        public string CercaDPObservacion { get; set; }
        public bool CheckLejos { get; set; }
        public bool CheckCerca { get; set; }
        public bool CheckCristalesLaboratorio { get; set; }
        public bool CheckUrgente { get; set; }
        public string RutCliente { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual OPT_Cliente OPT_Cliente { get; set; }
        public virtual OPT_OrdenDeTrabajo OPT_OrdenDeTrabajo { get; set; }
    }
}
