//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Cuota
    {
        public long idCuota { get; set; }
        public long idOT { get; set; }
        public int Numero { get; set; }
        public decimal ValorCuota { get; set; }
        public System.DateTime FechaBencimiento { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string TipoPago { get; set; }
        public string Estado { get; set; }
    
        public virtual OPT_OrdenDeTrabajo OPT_OrdenDeTrabajo { get; set; }
    }
}
