//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Atencion
    {
        public long idAtencion { get; set; }
        public string RutCliente { get; set; }
        public System.DateTime FechaAtencion { get; set; }
        public string Responsable { get; set; }
        public Nullable<long> idAnamnesis { get; set; }
        public Nullable<long> idRecetaCristales { get; set; }
        public Nullable<long> idOT { get; set; }
    
        public virtual OPT_Cliente OPT_Cliente { get; set; }
    }
}
