//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_OrdenDeTrabajoDetalle
    {
        public long idOTDetalle { get; set; }
        public long idOT { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
        public string Comentario { get; set; }
        public long idProducto { get; set; }
    
        public virtual OPT_OrdenDeTrabajo OPT_OrdenDeTrabajo { get; set; }
        public virtual OPT_Producto OPT_Producto { get; set; }
    }
}
