//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_Abono
    {
        public long idAbono { get; set; }
        public long idOT { get; set; }
        public int idFormaPago { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaAbono { get; set; }
    
        public virtual OPT_FormaPago OPT_FormaPago { get; set; }
        public virtual OPT_OrdenDeTrabajo OPT_OrdenDeTrabajo { get; set; }
    }
}
