//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_OrdenDeTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_OrdenDeTrabajo()
        {
            this.OPT_Abono = new HashSet<OPT_Abono>();
            this.OPT_Cuota = new HashSet<OPT_Cuota>();
            this.OPT_Pago = new HashSet<OPT_Pago>();
            this.OPT_RecetaCristales = new HashSet<OPT_RecetaCristales>();
            this.OPT_BitacoraOT = new HashSet<OPT_BitacoraOT>();
            this.OPT_OrdenDeTrabajoDetalle = new HashSet<OPT_OrdenDeTrabajoDetalle>();
        }
    
        public long idOT { get; set; }
        public string Beneficiario { get; set; }
        public string RutCliente { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.TimeSpan> HoraEntrega { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Abono { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> NumeroCuota { get; set; }
        public string EstadoPago { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string FormaAbono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_Abono> OPT_Abono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_Cuota> OPT_Cuota { get; set; }
        public virtual OPT_Empresa OPT_Empresa { get; set; }
        public virtual OPT_Sucursal OPT_Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_Pago> OPT_Pago { get; set; }
        public virtual OPT_Cliente OPT_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_RecetaCristales> OPT_RecetaCristales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_BitacoraOT> OPT_BitacoraOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_OrdenDeTrabajoDetalle> OPT_OrdenDeTrabajoDetalle { get; set; }
    }
}
