//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPT.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_EmpresaSucursal
    {
        public int idEmpresaSucursal { get; set; }
        public int idEmpresa { get; set; }
        public int idSucursal { get; set; }
    
        public virtual OPT_Sucursal OPT_Sucursal { get; set; }
        public virtual OPT_Empresa OPT_Empresa { get; set; }
    }
}
