<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OPT.API</RootNamespace>
    <UserSecretsId>5aa5a944-b381-44df-a2ed-6d2e7b1205c7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*" PrivateAssets="all" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OPT.Application\OPT.Application.csproj" />
    <ProjectReference Include="..\OPT.Infrastructure\OPT.Infrastructure.csproj" />
  </ItemGroup>
</Project>
