using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OPT.Domain.Entities.Organizacion;

namespace OPT.Infrastructure.Persistence.Configurations.Organizacion;

public sealed class ComunaConfiguration : IEntityTypeConfiguration<Comuna>
{
    public void Configure(EntityTypeBuilder<Comuna> builder)
    {
        builder.ToTable("OPT_Comuna");

        builder.HasKey(c => c.Id);

        builder.Property(c => c.Id)
               .ValueGeneratedNever(); // IDs fijos según datos INE

        builder.Property(c => c.Nombre)
               .IsRequired()
               .HasMaxLength(100);

        builder.Property(c => c.RegionId)
               .IsRequired();

        builder.HasIndex(c => c.RegionId)
               .HasDatabaseName("IX_Comunas_RegionId");

        // ── Seed: Comunas de Chile agrupadas por Región (fuente INE) ─────────
        builder.HasData(
            // I — Tarapacá (2 provincias, 7 comunas)
            new { Id =   1, Nombre = "Iquique",          RegionId =  1 },
            new { Id =   2, Nombre = "Alto Hospicio",    RegionId =  1 },
            new { Id =   3, Nombre = "Pozo Almonte",     RegionId =  1 },
            new { Id =   4, Nombre = "Camiña",           RegionId =  1 },
            new { Id =   5, Nombre = "Colchane",         RegionId =  1 },
            new { Id =   6, Nombre = "Huara",            RegionId =  1 },
            new { Id =   7, Nombre = "Pica",             RegionId =  1 },

            // II — Antofagasta (3 provincias, 9 comunas)
            new { Id =   8, Nombre = "Antofagasta",      RegionId =  2 },
            new { Id =   9, Nombre = "Mejillones",       RegionId =  2 },
            new { Id =  10, Nombre = "Sierra Gorda",     RegionId =  2 },
            new { Id =  11, Nombre = "Taltal",           RegionId =  2 },
            new { Id =  12, Nombre = "Calama",           RegionId =  2 },
            new { Id =  13, Nombre = "Ollagüe",          RegionId =  2 },
            new { Id =  14, Nombre = "San Pedro de Atacama", RegionId = 2 },
            new { Id =  15, Nombre = "Tocopilla",        RegionId =  2 },
            new { Id =  16, Nombre = "María Elena",      RegionId =  2 },

            // III — Atacama (3 provincias, 9 comunas)
            new { Id =  17, Nombre = "Copiapó",          RegionId =  3 },
            new { Id =  18, Nombre = "Caldera",          RegionId =  3 },
            new { Id =  19, Nombre = "Tierra Amarilla",  RegionId =  3 },
            new { Id =  20, Nombre = "Chañaral",         RegionId =  3 },
            new { Id =  21, Nombre = "Diego de Almagro", RegionId =  3 },
            new { Id =  22, Nombre = "Vallenar",         RegionId =  3 },
            new { Id =  23, Nombre = "Alto del Carmen",  RegionId =  3 },
            new { Id =  24, Nombre = "Freirina",         RegionId =  3 },
            new { Id =  25, Nombre = "Huasco",           RegionId =  3 },

            // IV — Coquimbo (3 provincias, 15 comunas)
            new { Id =  26, Nombre = "La Serena",        RegionId =  4 },
            new { Id =  27, Nombre = "Coquimbo",         RegionId =  4 },
            new { Id =  28, Nombre = "Andacollo",        RegionId =  4 },
            new { Id =  29, Nombre = "La Higuera",       RegionId =  4 },
            new { Id =  30, Nombre = "Paiguano",         RegionId =  4 },
            new { Id =  31, Nombre = "Vicuña",           RegionId =  4 },
            new { Id =  32, Nombre = "Illapel",          RegionId =  4 },
            new { Id =  33, Nombre = "Canela",           RegionId =  4 },
            new { Id =  34, Nombre = "Los Vilos",        RegionId =  4 },
            new { Id =  35, Nombre = "Salamanca",        RegionId =  4 },
            new { Id =  36, Nombre = "Ovalle",           RegionId =  4 },
            new { Id =  37, Nombre = "Combarbalá",       RegionId =  4 },
            new { Id =  38, Nombre = "Monte Patria",     RegionId =  4 },
            new { Id =  39, Nombre = "Punitaqui",        RegionId =  4 },
            new { Id =  40, Nombre = "Río Hurtado",      RegionId =  4 },

            // V — Valparaíso (8 provincias, 38 comunas)
            new { Id =  41, Nombre = "Valparaíso",       RegionId =  5 },
            new { Id =  42, Nombre = "Casablanca",       RegionId =  5 },
            new { Id =  43, Nombre = "Concón",           RegionId =  5 },
            new { Id =  44, Nombre = "Juan Fernández",   RegionId =  5 },
            new { Id =  45, Nombre = "Puchuncaví",       RegionId =  5 },
            new { Id =  46, Nombre = "Quintero",         RegionId =  5 },
            new { Id =  47, Nombre = "Viña del Mar",     RegionId =  5 },
            new { Id =  48, Nombre = "Isla de Pascua",   RegionId =  5 },
            new { Id =  49, Nombre = "Los Andes",        RegionId =  5 },
            new { Id =  50, Nombre = "Calle Larga",      RegionId =  5 },
            new { Id =  51, Nombre = "Rinconada",        RegionId =  5 },
            new { Id =  52, Nombre = "San Esteban",      RegionId =  5 },
            new { Id =  53, Nombre = "La Ligua",         RegionId =  5 },
            new { Id =  54, Nombre = "Cabildo",          RegionId =  5 },
            new { Id =  55, Nombre = "Papudo",           RegionId =  5 },
            new { Id =  56, Nombre = "Petorca",          RegionId =  5 },
            new { Id =  57, Nombre = "Zapallar",         RegionId =  5 },
            new { Id =  58, Nombre = "Quillota",         RegionId =  5 },
            new { Id =  59, Nombre = "Calera",           RegionId =  5 },
            new { Id =  60, Nombre = "Hijuelas",         RegionId =  5 },
            new { Id =  61, Nombre = "La Cruz",          RegionId =  5 },
            new { Id =  62, Nombre = "Nogales",          RegionId =  5 },
            new { Id =  63, Nombre = "San Antonio",      RegionId =  5 },
            new { Id =  64, Nombre = "Algarrobo",        RegionId =  5 },
            new { Id =  65, Nombre = "Cartagena",        RegionId =  5 },
            new { Id =  66, Nombre = "El Quisco",        RegionId =  5 },
            new { Id =  67, Nombre = "El Tabo",          RegionId =  5 },
            new { Id =  68, Nombre = "Santo Domingo",    RegionId =  5 },
            new { Id =  69, Nombre = "San Felipe",       RegionId =  5 },
            new { Id =  70, Nombre = "Catemu",           RegionId =  5 },
            new { Id =  71, Nombre = "Llaillay",         RegionId =  5 },
            new { Id =  72, Nombre = "Panquehue",        RegionId =  5 },
            new { Id =  73, Nombre = "Putaendo",         RegionId =  5 },
            new { Id =  74, Nombre = "Santa María",      RegionId =  5 },
            new { Id =  75, Nombre = "Quilpué",          RegionId =  5 },
            new { Id =  76, Nombre = "Limache",          RegionId =  5 },
            new { Id =  77, Nombre = "Olmué",            RegionId =  5 },
            new { Id =  78, Nombre = "Villa Alemana",    RegionId =  5 },

            // VI — O'Higgins (3 provincias, 33 comunas)
            new { Id =  79, Nombre = "Rancagua",         RegionId =  6 },
            new { Id =  80, Nombre = "Codegua",          RegionId =  6 },
            new { Id =  81, Nombre = "Coinco",           RegionId =  6 },
            new { Id =  82, Nombre = "Coltauco",         RegionId =  6 },
            new { Id =  83, Nombre = "Doñihue",          RegionId =  6 },
            new { Id =  84, Nombre = "Graneros",         RegionId =  6 },
            new { Id =  85, Nombre = "Las Cabras",       RegionId =  6 },
            new { Id =  86, Nombre = "Machalí",          RegionId =  6 },
            new { Id =  87, Nombre = "Malloa",           RegionId =  6 },
            new { Id =  88, Nombre = "Mostazal",         RegionId =  6 },
            new { Id =  89, Nombre = "Olivar",           RegionId =  6 },
            new { Id =  90, Nombre = "Peumo",            RegionId =  6 },
            new { Id =  91, Nombre = "Pichidegua",       RegionId =  6 },
            new { Id =  92, Nombre = "Quinta de Tilcoco",RegionId =  6 },
            new { Id =  93, Nombre = "Rengo",            RegionId =  6 },
            new { Id =  94, Nombre = "Requínoa",         RegionId =  6 },
            new { Id =  95, Nombre = "San Vicente",      RegionId =  6 },
            new { Id =  96, Nombre = "Pichilemu",        RegionId =  6 },
            new { Id =  97, Nombre = "La Estrella",      RegionId =  6 },
            new { Id =  98, Nombre = "Litueche",         RegionId =  6 },
            new { Id =  99, Nombre = "Marchihue",        RegionId =  6 },
            new { Id = 100, Nombre = "Navidad",          RegionId =  6 },
            new { Id = 101, Nombre = "Paredones",        RegionId =  6 },
            new { Id = 102, Nombre = "San Fernando",     RegionId =  6 },
            new { Id = 103, Nombre = "Chépica",          RegionId =  6 },
            new { Id = 104, Nombre = "Chimbarongo",      RegionId =  6 },
            new { Id = 105, Nombre = "Lolol",            RegionId =  6 },
            new { Id = 106, Nombre = "Nancagua",         RegionId =  6 },
            new { Id = 107, Nombre = "Palmilla",         RegionId =  6 },
            new { Id = 108, Nombre = "Peralillo",        RegionId =  6 },
            new { Id = 109, Nombre = "Placilla",         RegionId =  6 },
            new { Id = 110, Nombre = "Pumanque",         RegionId =  6 },
            new { Id = 111, Nombre = "Santa Cruz",       RegionId =  6 },

            // VII — Maule (4 provincias, 30 comunas)
            new { Id = 112, Nombre = "Talca",            RegionId =  7 },
            new { Id = 113, Nombre = "Constitución",     RegionId =  7 },
            new { Id = 114, Nombre = "Curepto",          RegionId =  7 },
            new { Id = 115, Nombre = "Empedrado",        RegionId =  7 },
            new { Id = 116, Nombre = "Maule",            RegionId =  7 },
            new { Id = 117, Nombre = "Pelarco",          RegionId =  7 },
            new { Id = 118, Nombre = "Pencahue",         RegionId =  7 },
            new { Id = 119, Nombre = "Río Claro",        RegionId =  7 },
            new { Id = 120, Nombre = "San Clemente",     RegionId =  7 },
            new { Id = 121, Nombre = "San Rafael",       RegionId =  7 },
            new { Id = 122, Nombre = "Cauquenes",        RegionId =  7 },
            new { Id = 123, Nombre = "Chanco",           RegionId =  7 },
            new { Id = 124, Nombre = "Pelluhue",         RegionId =  7 },
            new { Id = 125, Nombre = "Curicó",           RegionId =  7 },
            new { Id = 126, Nombre = "Hualañé",          RegionId =  7 },
            new { Id = 127, Nombre = "Licantén",         RegionId =  7 },
            new { Id = 128, Nombre = "Molina",           RegionId =  7 },
            new { Id = 129, Nombre = "Rauco",            RegionId =  7 },
            new { Id = 130, Nombre = "Romeral",          RegionId =  7 },
            new { Id = 131, Nombre = "Sagrada Familia",  RegionId =  7 },
            new { Id = 132, Nombre = "Teno",             RegionId =  7 },
            new { Id = 133, Nombre = "Vichuquén",        RegionId =  7 },
            new { Id = 134, Nombre = "Linares",          RegionId =  7 },
            new { Id = 135, Nombre = "Colbún",           RegionId =  7 },
            new { Id = 136, Nombre = "Longaví",          RegionId =  7 },
            new { Id = 137, Nombre = "Parral",           RegionId =  7 },
            new { Id = 138, Nombre = "Retiro",           RegionId =  7 },
            new { Id = 139, Nombre = "San Javier",       RegionId =  7 },
            new { Id = 140, Nombre = "Villa Alegre",     RegionId =  7 },
            new { Id = 141, Nombre = "Yerbas Buenas",    RegionId =  7 },

            // VIII — Biobío (3 provincias, 33 comunas)
            new { Id = 142, Nombre = "Concepción",       RegionId =  8 },
            new { Id = 143, Nombre = "Coronel",          RegionId =  8 },
            new { Id = 144, Nombre = "Chiguayante",      RegionId =  8 },
            new { Id = 145, Nombre = "Florida",          RegionId =  8 },
            new { Id = 146, Nombre = "Hualqui",          RegionId =  8 },
            new { Id = 147, Nombre = "Lota",             RegionId =  8 },
            new { Id = 148, Nombre = "Penco",            RegionId =  8 },
            new { Id = 149, Nombre = "San Pedro de la Paz", RegionId = 8 },
            new { Id = 150, Nombre = "Santa Juana",      RegionId =  8 },
            new { Id = 151, Nombre = "Talcahuano",       RegionId =  8 },
            new { Id = 152, Nombre = "Tomé",             RegionId =  8 },
            new { Id = 153, Nombre = "Hualpén",          RegionId =  8 },
            new { Id = 154, Nombre = "Lebu",             RegionId =  8 },
            new { Id = 155, Nombre = "Arauco",           RegionId =  8 },
            new { Id = 156, Nombre = "Cañete",           RegionId =  8 },
            new { Id = 157, Nombre = "Contulmo",         RegionId =  8 },
            new { Id = 158, Nombre = "Curanilahue",      RegionId =  8 },
            new { Id = 159, Nombre = "Los Álamos",       RegionId =  8 },
            new { Id = 160, Nombre = "Tirúa",            RegionId =  8 },
            new { Id = 161, Nombre = "Los Ángeles",      RegionId =  8 },
            new { Id = 162, Nombre = "Antuco",           RegionId =  8 },
            new { Id = 163, Nombre = "Cabrero",          RegionId =  8 },
            new { Id = 164, Nombre = "Laja",             RegionId =  8 },
            new { Id = 165, Nombre = "Mulchén",          RegionId =  8 },
            new { Id = 166, Nombre = "Nacimiento",       RegionId =  8 },
            new { Id = 167, Nombre = "Negrete",          RegionId =  8 },
            new { Id = 168, Nombre = "Quilaco",          RegionId =  8 },
            new { Id = 169, Nombre = "Quilleco",         RegionId =  8 },
            new { Id = 170, Nombre = "San Rosendo",      RegionId =  8 },
            new { Id = 171, Nombre = "Santa Bárbara",    RegionId =  8 },
            new { Id = 172, Nombre = "Tucapel",          RegionId =  8 },
            new { Id = 173, Nombre = "Yumbel",           RegionId =  8 },
            new { Id = 174, Nombre = "Alto Biobío",      RegionId =  8 },

            // IX — Araucanía (2 provincias, 32 comunas)
            new { Id = 175, Nombre = "Temuco",           RegionId =  9 },
            new { Id = 176, Nombre = "Carahue",          RegionId =  9 },
            new { Id = 177, Nombre = "Cunco",            RegionId =  9 },
            new { Id = 178, Nombre = "Curarrehue",       RegionId =  9 },
            new { Id = 179, Nombre = "Freire",           RegionId =  9 },
            new { Id = 180, Nombre = "Galvarino",        RegionId =  9 },
            new { Id = 181, Nombre = "Gorbea",           RegionId =  9 },
            new { Id = 182, Nombre = "Lautaro",          RegionId =  9 },
            new { Id = 183, Nombre = "Loncoche",         RegionId =  9 },
            new { Id = 184, Nombre = "Melipeuco",        RegionId =  9 },
            new { Id = 185, Nombre = "Nueva Imperial",   RegionId =  9 },
            new { Id = 186, Nombre = "Padre las Casas",  RegionId =  9 },
            new { Id = 187, Nombre = "Perquenco",        RegionId =  9 },
            new { Id = 188, Nombre = "Pitrufquén",       RegionId =  9 },
            new { Id = 189, Nombre = "Pucón",            RegionId =  9 },
            new { Id = 190, Nombre = "Saavedra",         RegionId =  9 },
            new { Id = 191, Nombre = "Teodoro Schmidt",  RegionId =  9 },
            new { Id = 192, Nombre = "Toltén",           RegionId =  9 },
            new { Id = 193, Nombre = "Vilcún",           RegionId =  9 },
            new { Id = 194, Nombre = "Villarrica",       RegionId =  9 },
            new { Id = 195, Nombre = "Cholchol",         RegionId =  9 },
            new { Id = 196, Nombre = "Angol",            RegionId =  9 },
            new { Id = 197, Nombre = "Collipulli",       RegionId =  9 },
            new { Id = 198, Nombre = "Curacautín",       RegionId =  9 },
            new { Id = 199, Nombre = "Ercilla",          RegionId =  9 },
            new { Id = 200, Nombre = "Lonquimay",        RegionId =  9 },
            new { Id = 201, Nombre = "Los Sauces",       RegionId =  9 },
            new { Id = 202, Nombre = "Lumaco",           RegionId =  9 },
            new { Id = 203, Nombre = "Purén",            RegionId =  9 },
            new { Id = 204, Nombre = "Renaico",          RegionId =  9 },
            new { Id = 205, Nombre = "Traiguén",         RegionId =  9 },
            new { Id = 206, Nombre = "Victoria",         RegionId =  9 },

            // X — Los Lagos (4 provincias, 30 comunas)
            new { Id = 207, Nombre = "Puerto Montt",     RegionId = 10 },
            new { Id = 208, Nombre = "Calbuco",          RegionId = 10 },
            new { Id = 209, Nombre = "Cochamó",          RegionId = 10 },
            new { Id = 210, Nombre = "Fresia",           RegionId = 10 },
            new { Id = 211, Nombre = "Frutillar",        RegionId = 10 },
            new { Id = 212, Nombre = "Los Muermos",      RegionId = 10 },
            new { Id = 213, Nombre = "Llanquihue",       RegionId = 10 },
            new { Id = 214, Nombre = "Maullín",          RegionId = 10 },
            new { Id = 215, Nombre = "Puerto Varas",     RegionId = 10 },
            new { Id = 216, Nombre = "Castro",           RegionId = 10 },
            new { Id = 217, Nombre = "Ancud",            RegionId = 10 },
            new { Id = 218, Nombre = "Chonchi",          RegionId = 10 },
            new { Id = 219, Nombre = "Curaco de Vélez",  RegionId = 10 },
            new { Id = 220, Nombre = "Dalcahue",         RegionId = 10 },
            new { Id = 221, Nombre = "Puqueldón",        RegionId = 10 },
            new { Id = 222, Nombre = "Queilén",          RegionId = 10 },
            new { Id = 223, Nombre = "Quellón",          RegionId = 10 },
            new { Id = 224, Nombre = "Quemchi",          RegionId = 10 },
            new { Id = 225, Nombre = "Quinchao",         RegionId = 10 },
            new { Id = 226, Nombre = "Osorno",           RegionId = 10 },
            new { Id = 227, Nombre = "Puerto Octay",     RegionId = 10 },
            new { Id = 228, Nombre = "Purranque",        RegionId = 10 },
            new { Id = 229, Nombre = "Puyehue",          RegionId = 10 },
            new { Id = 230, Nombre = "Río Negro",        RegionId = 10 },
            new { Id = 231, Nombre = "San Juan de la Costa", RegionId = 10 },
            new { Id = 232, Nombre = "San Pablo",        RegionId = 10 },
            new { Id = 233, Nombre = "Chaitén",          RegionId = 10 },
            new { Id = 234, Nombre = "Futaleufú",        RegionId = 10 },
            new { Id = 235, Nombre = "Hualaihué",        RegionId = 10 },
            new { Id = 236, Nombre = "Palena",           RegionId = 10 },

            // XI — Aysén (4 provincias, 10 comunas)
            new { Id = 237, Nombre = "Coyhaique",        RegionId = 11 },
            new { Id = 238, Nombre = "Lago Verde",       RegionId = 11 },
            new { Id = 239, Nombre = "Aysén",            RegionId = 11 },
            new { Id = 240, Nombre = "Cisnes",           RegionId = 11 },
            new { Id = 241, Nombre = "Guaitecas",        RegionId = 11 },
            new { Id = 242, Nombre = "Cochrane",         RegionId = 11 },
            new { Id = 243, Nombre = "O'Higgins",        RegionId = 11 },
            new { Id = 244, Nombre = "Tortel",           RegionId = 11 },
            new { Id = 245, Nombre = "Chile Chico",      RegionId = 11 },
            new { Id = 246, Nombre = "Río Ibáñez",       RegionId = 11 },

            // XII — Magallanes (4 provincias, 11 comunas)
            new { Id = 247, Nombre = "Punta Arenas",     RegionId = 12 },
            new { Id = 248, Nombre = "Laguna Blanca",    RegionId = 12 },
            new { Id = 249, Nombre = "Río Verde",        RegionId = 12 },
            new { Id = 250, Nombre = "San Gregorio",     RegionId = 12 },
            new { Id = 251, Nombre = "Cabo de Hornos",   RegionId = 12 },
            new { Id = 252, Nombre = "Antártica",        RegionId = 12 },
            new { Id = 253, Nombre = "Porvenir",         RegionId = 12 },
            new { Id = 254, Nombre = "Primavera",        RegionId = 12 },
            new { Id = 255, Nombre = "Timaukel",         RegionId = 12 },
            new { Id = 256, Nombre = "Natales",          RegionId = 12 },
            new { Id = 257, Nombre = "Torres del Paine", RegionId = 12 },

            // XIII — Metropolitana (6 provincias, 52 comunas)
            new { Id = 258, Nombre = "Santiago",         RegionId = 13 },
            new { Id = 259, Nombre = "Cerrillos",        RegionId = 13 },
            new { Id = 260, Nombre = "Cerro Navia",      RegionId = 13 },
            new { Id = 261, Nombre = "Conchalí",         RegionId = 13 },
            new { Id = 262, Nombre = "El Bosque",        RegionId = 13 },
            new { Id = 263, Nombre = "Estación Central", RegionId = 13 },
            new { Id = 264, Nombre = "Huechuraba",       RegionId = 13 },
            new { Id = 265, Nombre = "Independencia",    RegionId = 13 },
            new { Id = 266, Nombre = "La Cisterna",      RegionId = 13 },
            new { Id = 267, Nombre = "La Florida",       RegionId = 13 },
            new { Id = 268, Nombre = "La Granja",        RegionId = 13 },
            new { Id = 269, Nombre = "La Pintana",       RegionId = 13 },
            new { Id = 270, Nombre = "La Reina",         RegionId = 13 },
            new { Id = 271, Nombre = "Las Condes",       RegionId = 13 },
            new { Id = 272, Nombre = "Lo Barnechea",     RegionId = 13 },
            new { Id = 273, Nombre = "Lo Espejo",        RegionId = 13 },
            new { Id = 274, Nombre = "Lo Prado",         RegionId = 13 },
            new { Id = 275, Nombre = "Macul",            RegionId = 13 },
            new { Id = 276, Nombre = "Maipú",            RegionId = 13 },
            new { Id = 277, Nombre = "Ñuñoa",            RegionId = 13 },
            new { Id = 278, Nombre = "Pedro Aguirre Cerda", RegionId = 13 },
            new { Id = 279, Nombre = "Peñalolén",        RegionId = 13 },
            new { Id = 280, Nombre = "Providencia",      RegionId = 13 },
            new { Id = 281, Nombre = "Pudahuel",         RegionId = 13 },
            new { Id = 282, Nombre = "Quilicura",        RegionId = 13 },
            new { Id = 283, Nombre = "Quinta Normal",    RegionId = 13 },
            new { Id = 284, Nombre = "Recoleta",         RegionId = 13 },
            new { Id = 285, Nombre = "Renca",            RegionId = 13 },
            new { Id = 286, Nombre = "San Joaquín",      RegionId = 13 },
            new { Id = 287, Nombre = "San Miguel",       RegionId = 13 },
            new { Id = 288, Nombre = "San Ramón",        RegionId = 13 },
            new { Id = 289, Nombre = "Vitacura",         RegionId = 13 },
            new { Id = 290, Nombre = "Puente Alto",      RegionId = 13 },
            new { Id = 291, Nombre = "Pirque",           RegionId = 13 },
            new { Id = 292, Nombre = "San José de Maipo",RegionId = 13 },
            new { Id = 293, Nombre = "Colina",           RegionId = 13 },
            new { Id = 294, Nombre = "Lampa",            RegionId = 13 },
            new { Id = 295, Nombre = "Tiltil",           RegionId = 13 },
            new { Id = 296, Nombre = "San Bernardo",     RegionId = 13 },
            new { Id = 297, Nombre = "Buin",             RegionId = 13 },
            new { Id = 298, Nombre = "Calera de Tango",  RegionId = 13 },
            new { Id = 299, Nombre = "Paine",            RegionId = 13 },
            new { Id = 300, Nombre = "Melipilla",        RegionId = 13 },
            new { Id = 301, Nombre = "Alhué",            RegionId = 13 },
            new { Id = 302, Nombre = "Curacaví",         RegionId = 13 },
            new { Id = 303, Nombre = "María Pinto",      RegionId = 13 },
            new { Id = 304, Nombre = "San Pedro",        RegionId = 13 },
            new { Id = 305, Nombre = "Talagante",        RegionId = 13 },
            new { Id = 306, Nombre = "El Monte",         RegionId = 13 },
            new { Id = 307, Nombre = "Isla de Maipo",    RegionId = 13 },
            new { Id = 308, Nombre = "Padre Hurtado",    RegionId = 13 },
            new { Id = 309, Nombre = "Peñaflor",         RegionId = 13 },

            // XIV — Los Ríos (2 provincias, 12 comunas)
            new { Id = 310, Nombre = "Valdivia",         RegionId = 14 },
            new { Id = 311, Nombre = "Corral",           RegionId = 14 },
            new { Id = 312, Nombre = "Futrono",          RegionId = 14 },
            new { Id = 313, Nombre = "La Unión",         RegionId = 14 },
            new { Id = 314, Nombre = "Lago Ranco",       RegionId = 14 },
            new { Id = 315, Nombre = "Lanco",            RegionId = 14 },
            new { Id = 316, Nombre = "Los Lagos",        RegionId = 14 },
            new { Id = 317, Nombre = "Máfil",            RegionId = 14 },
            new { Id = 318, Nombre = "Mariquina",        RegionId = 14 },
            new { Id = 319, Nombre = "Paillaco",         RegionId = 14 },
            new { Id = 320, Nombre = "Panguipulli",      RegionId = 14 },
            new { Id = 321, Nombre = "Río Bueno",        RegionId = 14 },

            // XV — Arica y Parinacota (2 provincias, 4 comunas)
            new { Id = 322, Nombre = "Arica",            RegionId = 15 },
            new { Id = 323, Nombre = "Camarones",        RegionId = 15 },
            new { Id = 324, Nombre = "Putre",            RegionId = 15 },
            new { Id = 325, Nombre = "General Lagos",    RegionId = 15 },

            // XVI — Ñuble (3 provincias, 21 comunas)
            new { Id = 326, Nombre = "Chillán",          RegionId = 16 },
            new { Id = 327, Nombre = "Bulnes",           RegionId = 16 },
            new { Id = 328, Nombre = "Chillán Viejo",    RegionId = 16 },
            new { Id = 329, Nombre = "El Carmen",        RegionId = 16 },
            new { Id = 330, Nombre = "Pemuco",           RegionId = 16 },
            new { Id = 331, Nombre = "Pinto",            RegionId = 16 },
            new { Id = 332, Nombre = "Quillón",          RegionId = 16 },
            new { Id = 333, Nombre = "San Ignacio",      RegionId = 16 },
            new { Id = 334, Nombre = "Yungay",           RegionId = 16 },
            new { Id = 335, Nombre = "Quirihue",         RegionId = 16 },
            new { Id = 336, Nombre = "Cobquecura",       RegionId = 16 },
            new { Id = 337, Nombre = "Coelemu",          RegionId = 16 },
            new { Id = 338, Nombre = "Ninhue",           RegionId = 16 },
            new { Id = 339, Nombre = "Portezuelo",       RegionId = 16 },
            new { Id = 340, Nombre = "Ránquil",          RegionId = 16 },
            new { Id = 341, Nombre = "Treguaco",         RegionId = 16 },
            new { Id = 342, Nombre = "San Carlos",       RegionId = 16 },
            new { Id = 343, Nombre = "Coihueco",         RegionId = 16 },
            new { Id = 344, Nombre = "Ñiquén",           RegionId = 16 },
            new { Id = 345, Nombre = "San Fabián",       RegionId = 16 },
            new { Id = 346, Nombre = "San Nicolás",      RegionId = 16 }
        );
    }
}
